package com.drools.accountmanagement.loan.entity;

import jakarta.persistence.Entity;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LoanApplication implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private java.lang.String applicantName;

    private java.lang.Integer creditScore;

    private java.lang.Double income;

    private java.lang.Double loanAmount;

    private java.lang.String decision;

    private java.lang.String status;

    public LoanApplication() {
    }

    public java.lang.String getApplicantName() {
        return this.applicantName;
    }

    public void setApplicantName(java.lang.String applicantName) {
        this.applicantName = applicantName;
    }

    public java.lang.Integer getCreditScore() {
        return this.creditScore;
    }

    public void setCreditScore(java.lang.Integer creditScore) {
        this.creditScore = creditScore;
    }

    public java.lang.Double getIncome() {
        return this.income;
    }

    public void setIncome(java.lang.Double income) {
        this.income = income;
    }

    public java.lang.Double getLoanAmount() {
        return this.loanAmount;
    }

    public void setLoanAmount(java.lang.Double loanAmount) {
        this.loanAmount = loanAmount;
    }

    public java.lang.String getDecision() {
        return this.decision;
    }

    public void setDecision(java.lang.String decision) {
        this.decision = decision;
    }

    public java.lang.String getStatus() {
        return this.status;
    }

    public void setStatus(java.lang.String status) {
        this.status = status;
    }

    public LoanApplication(java.lang.String applicantName,
                           java.lang.Integer creditScore, java.lang.Double income,
                           java.lang.Double loanAmount, java.lang.String decision,
                           java.lang.String status) {
        this.applicantName = applicantName;
        this.creditScore = creditScore;
        this.income = income;
        this.loanAmount = loanAmount;
        this.decision = decision;
        this.status = status;
    }

}